// SPDX-FileCopyrightText: 2026 SBRO
// SPDX-License-Identifier: LicenseRef-EmuCoreA-Proprietary
//
// Generated from core/libretro/libretro_core_options.h (PPSSPP libretro core).
// Regenerate with: python tools/gen_ppsspp_options.py
package com.sbro.emucorea.core

@Suppress("MagicNumber")
object PpssppCoreOptions {
    data class Choice(val value: String, val label: String)

    data class Option(
        val key: String,
        val label: String,
        val category: String,
        val choices: List<Choice>,
        val defaultValue: String,
    ) {
        /** The option's short key without the `ppsspp_` prefix. */
        val shortKey: String get() = key.removePrefix("ppsspp_")

        /** True for plain on/off options whose only values are enabled/disabled. */
        val isBooleanToggle: Boolean
            get() = choices.map { it.value.lowercase() }.toSet() == setOf("enabled", "disabled")

        private val enabledValue: String?
            get() = choices.firstOrNull { it.value.equals("enabled", ignoreCase = true) }?.value

        private val disabledValue: String?
            get() = choices.firstOrNull { it.value.equals("disabled", ignoreCase = true) }?.value

        /** Reads a persisted value with the enabled/disabled and true/false conventions. */
        fun isEnabled(current: String?): Boolean = current != null &&
            (current.equals(enabledValue, ignoreCase = true) || current.equals("true", ignoreCase = true))

        /** Value to persist for a toggle interaction. */
        fun valueForEnabled(enabled: Boolean): String = if (enabled) {
            enabledValue ?: "true"
        } else {
            disabledValue ?: "false"
        }
    }

    data class Category(val key: String, val label: String, val description: String)

    private val categoryList: List<Category> = listOf(
        Category("system", "System", "Configure system options."),
        Category("video", "Video", "Configure video options."),
        Category("input", "Input", "Configure input options."),
        Category("hacks", "Hacks", "Configure speed and emulation hacks. Can cause rendering errors!"),
        Category("network", "Network", "Configure network options."),
    )

    private val optionList: List<Option> = listOf(
        // system
        Option(
            key = "ppsspp_cpu_core",
            label = "CPU Core",
            category = "system",
            choices = listOf(
                Choice("JIT", "Dynarec (JIT)"),
                Choice("IR JIT", "IR Interpreter"),
                Choice("Interpreter", "Interpreter"),
            ),
            defaultValue = "JIT",
        ),
        Option(
            key = "ppsspp_fast_memory",
            label = "Fast Memory",
            category = "system",
            choices = listOf(
                Choice("disabled", "disabled"),
                Choice("enabled", "enabled"),
            ),
            defaultValue = "enabled",
        ),
        Option(
            key = "ppsspp_ignore_bad_memory_access",
            label = "Ignore Bad Memory Accesses",
            category = "system",
            choices = listOf(
                Choice("disabled", "disabled"),
                Choice("enabled", "enabled"),
            ),
            defaultValue = "enabled",
        ),
        Option(
            key = "ppsspp_io_timing_method",
            label = "I/O Timing Method",
            category = "system",
            choices = listOf(
                Choice("Fast", "Fast"),
                Choice("Host", "Host"),
                Choice("Simulate UMD delays", "Simulate UMD delays"),
            ),
            defaultValue = "Fast",
        ),
        Option(
            key = "ppsspp_force_lag_sync",
            label = "Force Real Clock Sync",
            category = "system",
            choices = listOf(
                Choice("disabled", "disabled"),
                Choice("enabled", "enabled"),
            ),
            defaultValue = "disabled",
        ),
        Option(
            key = "ppsspp_locked_cpu_speed",
            label = "Locked CPU Speed",
            category = "system",
            choices = listOf(
                Choice("disabled", "disabled"),
                Choice("222MHz", "222MHz"),
                Choice("266MHz", "266MHz"),
                Choice("333MHz", "333MHz"),
                Choice("366MHz", "366MHz"),
                Choice("399MHz", "399MHz"),
                Choice("432MHz", "432MHz"),
                Choice("444MHz", "444MHz"),
                Choice("466MHz", "466MHz"),
                Choice("499MHz", "499MHz"),
                Choice("532MHz", "532MHz"),
                Choice("555MHz", "555MHz"),
                Choice("566MHz", "566MHz"),
                Choice("599MHz", "599MHz"),
                Choice("632MHz", "632MHz"),
                Choice("666MHz", "666MHz"),
                Choice("777MHz", "777MHz"),
                Choice("888MHz", "888MHz"),
                Choice("999MHz", "999MHz"),
            ),
            defaultValue = "disabled",
        ),
        Option(
            key = "ppsspp_memstick_inserted",
            label = "Memory Stick Inserted",
            category = "system",
            choices = listOf(
                Choice("disabled", "disabled"),
                Choice("enabled", "enabled"),
            ),
            defaultValue = "enabled",
        ),
        Option(
            key = "ppsspp_memstick_size",
            label = "Memory Stick size",
            category = "system",
            choices = listOf(1, 2, 4, 8, 16, 32, 64, 128).map { Choice(it.toString(), "${it}GB") },
            defaultValue = "16",
        ),
        Option(
            key = "ppsspp_cache_iso",
            label = "Cache Full ISO in RAM",
            category = "system",
            choices = listOf(
                Choice("disabled", "disabled"),
                Choice("enabled", "enabled"),
            ),
            defaultValue = "disabled",
        ),
        Option(
            key = "ppsspp_cheats",
            label = "Internal Cheats Support",
            category = "system",
            choices = listOf(
                Choice("disabled", "disabled"),
                Choice("enabled", "enabled"),
            ),
            defaultValue = "disabled",
        ),
        Option(
            key = "ppsspp_language",
            label = "Game Language",
            category = "system",
            choices = listOf(
                Choice("Automatic", "Automatic"),
                Choice("English", "English"),
                Choice("Japanese", "Japanese"),
                Choice("French", "French"),
                Choice("Spanish", "Spanish"),
                Choice("German", "German"),
                Choice("Italian", "Italian"),
                Choice("Dutch", "Dutch"),
                Choice("Portuguese", "Portuguese"),
                Choice("Russian", "Russian"),
                Choice("Korean", "Korean"),
                Choice("Chinese Traditional", "Chinese Traditional"),
                Choice("Chinese Simplified", "Chinese Simplified"),
            ),
            defaultValue = "Automatic",
        ),
        Option(
            key = "ppsspp_psp_model",
            label = "PSP Model",
            category = "system",
            choices = listOf(
                Choice("psp_1000", "PSP-1000"),
                Choice("psp_2000_3000", "PSP-2000/3000"),
            ),
            defaultValue = "psp_2000_3000",
        ),
        // video
        Option(
            key = "ppsspp_backend",
            label = "Backend",
            category = "video",
            choices = listOf(
                Choice("auto", "Automatic"),
                Choice("opengl", "OpenGL"),
                Choice("vulkan", "Vulkan"),
            ),
            defaultValue = "auto",
        ),
        Option(
            key = "ppsspp_software_rendering",
            label = "Software Rendering",
            category = "video",
            choices = listOf(
                Choice("disabled", "disabled"),
                Choice("enabled", "enabled"),
            ),
            defaultValue = "disabled",
        ),
        Option(
            key = "ppsspp_internal_resolution",
            label = "Rendering Resolution",
            category = "video",
            choices = listOf(
                Choice("480x272", "1x (480x272)"),
                Choice("960x544", "2x (960x544)"),
                Choice("1440x816", "3x (1440x816)"),
                Choice("1920x1088", "4x (1920x1088)"),
                Choice("2400x1360", "5x (2400x1360)"),
                Choice("2880x1632", "6x (2880x1632)"),
                Choice("3360x1904", "7x (3360x1904)"),
                Choice("3840x2176", "8x (3840x2176)"),
                Choice("4320x2448", "9x (4320x2448)"),
                Choice("4800x2720", "10x (4800x2720)"),
            ),
            defaultValue = "480x272",
        ),
        Option(
            key = "ppsspp_mulitsample_level",
            label = "MSAA Antialiasing",
            category = "video",
            choices = listOf(
                Choice("Disabled", "Disabled"),
                Choice("x2", "x2"),
                Choice("x4", "x4"),
                Choice("x8", "x8"),
            ),
            defaultValue = "Disabled",
        ),
        Option(
            key = "ppsspp_cropto16x9",
            label = "Crop to 16x9",
            category = "video",
            choices = listOf(
                Choice("disabled", "disabled"),
                Choice("enabled", "enabled"),
            ),
            defaultValue = "enabled",
        ),
        Option(
            key = "ppsspp_frameskip",
            label = "Frameskip",
            category = "video",
            choices = listOf(
                Choice("disabled", "disabled"),
                Choice("1", "1"),
                Choice("2", "2"),
                Choice("3", "3"),
                Choice("4", "4"),
                Choice("5", "5"),
                Choice("6", "6"),
                Choice("7", "7"),
                Choice("8", "8"),
            ),
            defaultValue = "disabled",
        ),
        Option(
            key = "ppsspp_auto_frameskip",
            label = "Auto Frameskip",
            category = "video",
            choices = listOf(
                Choice("disabled", "disabled"),
                Choice("enabled", "enabled"),
            ),
            defaultValue = "disabled",
        ),
        Option(
            key = "ppsspp_frame_duplication",
            label = "Render Duplicate Frames to 60 Hz",
            category = "video",
            choices = listOf(
                Choice("disabled", "disabled"),
                Choice("enabled", "enabled"),
            ),
            defaultValue = "disabled",
        ),
        Option(
            key = "ppsspp_detect_vsync_swap_interval",
            label = "Detect Frame Rate Changes",
            category = "video",
            choices = listOf(
                Choice("disabled", "disabled"),
                Choice("enabled", "enabled"),
            ),
            defaultValue = "disabled",
        ),
        Option(
            key = "ppsspp_inflight_frames",
            label = "Buffer Graphics Commands",
            category = "video",
            choices = listOf(
                Choice("No buffer", "No buffer"),
                Choice("Up to 1", "Up to 1"),
            ),
            defaultValue = "Up to 1",
        ),
        // input
        Option(
            key = "ppsspp_button_preference",
            label = "Confirmation Button",
            category = "input",
            choices = listOf(
                Choice("Cross", "Cross"),
                Choice("Circle", "Circle"),
            ),
            defaultValue = "Cross",
        ),
        Option(
            key = "ppsspp_analog_is_circular",
            label = "Analog Circle vs Square Gate Compensation",
            category = "input",
            choices = listOf(
                Choice("disabled", "disabled"),
                Choice("enabled", "enabled"),
            ),
            defaultValue = "disabled",
        ),
        Option(
            key = "ppsspp_analog_deadzone",
            label = "Analog Deadzone",
            category = "input",
            choices = listOf(
                Choice("0.0", "0%"),
                Choice("0.05", "5%"),
                Choice("0.10", "10%"),
                Choice("0.15", "15%"),
                Choice("0.20", "20%"),
                Choice("0.25", "25%"),
                Choice("0.30", "30%"),
                Choice("0.35", "35%"),
                Choice("0.40", "40%"),
                Choice("0.45", "45%"),
                Choice("0.50", "50%"),
            ),
            defaultValue = "0.0",
        ),
        Option(
            key = "ppsspp_analog_sensitivity",
            label = "Analog Axis Scale",
            category = "input",
            choices = listOf(
                Choice("1.00", "1.00"),
                Choice("1.01", "1.01"),
                Choice("1.02", "1.02"),
                Choice("1.03", "1.03"),
                Choice("1.04", "1.04"),
                Choice("1.05", "1.05"),
                Choice("1.06", "1.06"),
                Choice("1.07", "1.07"),
                Choice("1.08", "1.08"),
                Choice("1.09", "1.09"),
                Choice("1.10", "1.10"),
                Choice("1.11", "1.11"),
                Choice("1.12", "1.12"),
                Choice("1.13", "1.13"),
                Choice("1.14", "1.14"),
                Choice("1.15", "1.15"),
                Choice("1.16", "1.16"),
                Choice("1.17", "1.17"),
                Choice("1.18", "1.18"),
                Choice("1.19", "1.19"),
                Choice("1.20", "1.20"),
                Choice("1.21", "1.21"),
                Choice("1.22", "1.22"),
                Choice("1.23", "1.23"),
                Choice("1.24", "1.24"),
                Choice("1.25", "1.25"),
                Choice("1.26", "1.26"),
                Choice("1.27", "1.27"),
                Choice("1.28", "1.28"),
                Choice("1.29", "1.29"),
                Choice("1.30", "1.30"),
                Choice("1.31", "1.31"),
                Choice("1.32", "1.32"),
                Choice("1.33", "1.33"),
                Choice("1.34", "1.34"),
                Choice("1.35", "1.35"),
                Choice("1.36", "1.36"),
                Choice("1.37", "1.37"),
                Choice("1.38", "1.38"),
                Choice("1.39", "1.39"),
                Choice("1.40", "1.40"),
                Choice("1.41", "1.41"),
                Choice("1.42", "1.42"),
                Choice("1.43", "1.43"),
                Choice("1.44", "1.44"),
                Choice("1.45", "1.45"),
                Choice("1.46", "1.46"),
                Choice("1.47", "1.47"),
                Choice("1.48", "1.48"),
                Choice("1.49", "1.49"),
                Choice("1.50", "1.50"),
            ),
            defaultValue = "1.00",
        ),
        // hacks
        Option(
            key = "ppsspp_skip_buffer_effects",
            label = "Skip Buffer Effects",
            category = "hacks",
            choices = listOf(
                Choice("disabled", "disabled"),
                Choice("enabled", "enabled"),
            ),
            defaultValue = "disabled",
        ),
        Option(
            key = "ppsspp_skip_gpu_readbacks",
            label = "Skip GPU Readbacks",
            category = "hacks",
            choices = listOf(
                Choice("disabled", "disabled"),
                Choice("enabled", "enabled"),
            ),
            defaultValue = "disabled",
        ),
        Option(
            key = "ppsspp_spline_quality",
            label = "Spline/Bezier Curves Quality",
            category = "hacks",
            choices = listOf(
                Choice("Low", "Low"),
                Choice("Medium", "Medium"),
                Choice("High", "High"),
            ),
            defaultValue = "High",
        ),
        Option(
            key = "ppsspp_lower_resolution_for_effects",
            label = "Lower Resolution for Effects",
            category = "hacks",
            choices = listOf(
                Choice("disabled", "disabled"),
                Choice("Safe", "Safe"),
                Choice("Balanced", "Balanced"),
                Choice("Aggressive", "Aggressive"),
            ),
            defaultValue = "disabled",
        ),
        // video
        Option(
            key = "ppsspp_gpu_hardware_transform",
            label = "Hardware Transform",
            category = "video",
            choices = listOf(
                Choice("disabled", "disabled"),
                Choice("enabled", "enabled"),
            ),
            defaultValue = "enabled",
        ),
        Option(
            key = "ppsspp_texture_scaling_type",
            label = "Texture Upscale Type",
            category = "video",
            choices = listOf(
                Choice("xbrz", "xBRZ"),
                Choice("hybrid", "Hybrid"),
                Choice("bicubic", "Bicubic"),
                Choice("hybrid_bicubic", "Hybrid + Bicubic"),
            ),
            defaultValue = "xbrz",
        ),
        Option(
            key = "ppsspp_texture_scaling_level",
            label = "Texture Upscaling Level",
            category = "video",
            choices = listOf(
                Choice("disabled", "disabled"),
                Choice("2x", "2x"),
                Choice("3x", "3x"),
                Choice("4x", "4x"),
                Choice("5x", "5x"),
            ),
            defaultValue = "disabled",
        ),
        Option(
            key = "ppsspp_texture_deposterize",
            label = "Texture Deposterize",
            category = "video",
            choices = listOf(
                Choice("disabled", "disabled"),
                Choice("enabled", "enabled"),
            ),
            defaultValue = "disabled",
        ),
        Option(
            key = "ppsspp_texture_shader",
            label = "Texture Shader",
            category = "video",
            choices = listOf(
                Choice("disabled", "disabled"),
                Choice("2xBRZ", "Tex2xBRZ"),
                Choice("4xBRZ", "Tex4xBRZ"),
                Choice("MMPX", "TexMMPX"),
            ),
            defaultValue = "disabled",
        ),
        Option(
            key = "ppsspp_texture_anisotropic_filtering",
            label = "Anisotropic Filtering",
            category = "video",
            choices = listOf(
                Choice("disabled", "disabled"),
                Choice("2x", "2x"),
                Choice("4x", "4x"),
                Choice("8x", "8x"),
                Choice("16x", "16x"),
            ),
            defaultValue = "16x",
        ),
        Option(
            key = "ppsspp_texture_filtering",
            label = "Texture Filtering",
            category = "video",
            choices = listOf(
                Choice("Auto", "Auto"),
                Choice("Nearest", "Nearest"),
                Choice("Linear", "Linear"),
                Choice("Auto max quality", "Auto max quality"),
            ),
            defaultValue = "Auto",
        ),
        Option(
            key = "ppsspp_smart_2d_texture_filtering",
            label = "Smart 2D Texture Filtering",
            category = "video",
            choices = listOf(
                Choice("disabled", "disabled"),
                Choice("enabled", "enabled"),
            ),
            defaultValue = "disabled",
        ),
        Option(
            key = "ppsspp_texture_replacement",
            label = "Texture Replacement",
            category = "video",
            choices = listOf(
                Choice("disabled", "disabled"),
                Choice("enabled", "enabled"),
            ),
            defaultValue = "disabled",
        ),
        // network
        Option(
            key = "ppsspp_enable_wlan",
            label = "Enable Networking/WLAN (Beta, may break games)",
            category = "network",
            choices = listOf(
                Choice("disabled", "disabled"),
                Choice("enabled", "enabled"),
            ),
            defaultValue = "disabled",
        ),
        Option(
            key = "ppsspp_change_mac_address01",
            label = "MAC Address Pt  1: x-:--:--:--:--:--",
            category = "network",
            choices = listOf(
                Choice("0", "0"),
                Choice("1", "1"),
                Choice("2", "2"),
                Choice("3", "3"),
                Choice("4", "4"),
                Choice("5", "5"),
                Choice("6", "6"),
                Choice("7", "7"),
                Choice("8", "8"),
                Choice("9", "9"),
                Choice("a", "a"),
                Choice("b", "b"),
                Choice("c", "c"),
                Choice("d", "d"),
                Choice("e", "e"),
                Choice("f", "f"),
            ),
            defaultValue = "0",
        ),
        Option(
            key = "ppsspp_change_mac_address02",
            label = "MAC Address Pt  2: -x:--:--:--:--:--",
            category = "network",
            choices = listOf(
                Choice("0", "0"),
                Choice("1", "1"),
                Choice("2", "2"),
                Choice("3", "3"),
                Choice("4", "4"),
                Choice("5", "5"),
                Choice("6", "6"),
                Choice("7", "7"),
                Choice("8", "8"),
                Choice("9", "9"),
                Choice("a", "a"),
                Choice("b", "b"),
                Choice("c", "c"),
                Choice("d", "d"),
                Choice("e", "e"),
                Choice("f", "f"),
            ),
            defaultValue = "0",
        ),
        Option(
            key = "ppsspp_change_mac_address03",
            label = "MAC Address Pt  3: --:x-:--:--:--:--",
            category = "network",
            choices = listOf(
                Choice("0", "0"),
                Choice("1", "1"),
                Choice("2", "2"),
                Choice("3", "3"),
                Choice("4", "4"),
                Choice("5", "5"),
                Choice("6", "6"),
                Choice("7", "7"),
                Choice("8", "8"),
                Choice("9", "9"),
                Choice("a", "a"),
                Choice("b", "b"),
                Choice("c", "c"),
                Choice("d", "d"),
                Choice("e", "e"),
                Choice("f", "f"),
            ),
            defaultValue = "0",
        ),
        Option(
            key = "ppsspp_change_mac_address04",
            label = "MAC Address Pt  4: --:-x:--:--:--:--",
            category = "network",
            choices = listOf(
                Choice("0", "0"),
                Choice("1", "1"),
                Choice("2", "2"),
                Choice("3", "3"),
                Choice("4", "4"),
                Choice("5", "5"),
                Choice("6", "6"),
                Choice("7", "7"),
                Choice("8", "8"),
                Choice("9", "9"),
                Choice("a", "a"),
                Choice("b", "b"),
                Choice("c", "c"),
                Choice("d", "d"),
                Choice("e", "e"),
                Choice("f", "f"),
            ),
            defaultValue = "0",
        ),
        Option(
            key = "ppsspp_change_mac_address05",
            label = "MAC Address Pt  5: --:--:x-:--:--:--",
            category = "network",
            choices = listOf(
                Choice("0", "0"),
                Choice("1", "1"),
                Choice("2", "2"),
                Choice("3", "3"),
                Choice("4", "4"),
                Choice("5", "5"),
                Choice("6", "6"),
                Choice("7", "7"),
                Choice("8", "8"),
                Choice("9", "9"),
                Choice("a", "a"),
                Choice("b", "b"),
                Choice("c", "c"),
                Choice("d", "d"),
                Choice("e", "e"),
                Choice("f", "f"),
            ),
            defaultValue = "0",
        ),
        Option(
            key = "ppsspp_change_mac_address06",
            label = "MAC Address Pt  6: --:--:-x:--:--:--",
            category = "network",
            choices = listOf(
                Choice("0", "0"),
                Choice("1", "1"),
                Choice("2", "2"),
                Choice("3", "3"),
                Choice("4", "4"),
                Choice("5", "5"),
                Choice("6", "6"),
                Choice("7", "7"),
                Choice("8", "8"),
                Choice("9", "9"),
                Choice("a", "a"),
                Choice("b", "b"),
                Choice("c", "c"),
                Choice("d", "d"),
                Choice("e", "e"),
                Choice("f", "f"),
            ),
            defaultValue = "0",
        ),
        Option(
            key = "ppsspp_change_mac_address07",
            label = "MAC Address Pt  7: --:--:--:x-:--:--",
            category = "network",
            choices = listOf(
                Choice("0", "0"),
                Choice("1", "1"),
                Choice("2", "2"),
                Choice("3", "3"),
                Choice("4", "4"),
                Choice("5", "5"),
                Choice("6", "6"),
                Choice("7", "7"),
                Choice("8", "8"),
                Choice("9", "9"),
                Choice("a", "a"),
                Choice("b", "b"),
                Choice("c", "c"),
                Choice("d", "d"),
                Choice("e", "e"),
                Choice("f", "f"),
            ),
            defaultValue = "0",
        ),
        Option(
            key = "ppsspp_change_mac_address08",
            label = "MAC Address Pt  8: --:--:--:-x:--:--",
            category = "network",
            choices = listOf(
                Choice("0", "0"),
                Choice("1", "1"),
                Choice("2", "2"),
                Choice("3", "3"),
                Choice("4", "4"),
                Choice("5", "5"),
                Choice("6", "6"),
                Choice("7", "7"),
                Choice("8", "8"),
                Choice("9", "9"),
                Choice("a", "a"),
                Choice("b", "b"),
                Choice("c", "c"),
                Choice("d", "d"),
                Choice("e", "e"),
                Choice("f", "f"),
            ),
            defaultValue = "0",
        ),
        Option(
            key = "ppsspp_change_mac_address09",
            label = "MAC Address Pt  9: --:--:--:--:x-:--",
            category = "network",
            choices = listOf(
                Choice("0", "0"),
                Choice("1", "1"),
                Choice("2", "2"),
                Choice("3", "3"),
                Choice("4", "4"),
                Choice("5", "5"),
                Choice("6", "6"),
                Choice("7", "7"),
                Choice("8", "8"),
                Choice("9", "9"),
                Choice("a", "a"),
                Choice("b", "b"),
                Choice("c", "c"),
                Choice("d", "d"),
                Choice("e", "e"),
                Choice("f", "f"),
            ),
            defaultValue = "0",
        ),
        Option(
            key = "ppsspp_change_mac_address10",
            label = "MAC Address Pt 10: --:--:--:--:-x:--",
            category = "network",
            choices = listOf(
                Choice("0", "0"),
                Choice("1", "1"),
                Choice("2", "2"),
                Choice("3", "3"),
                Choice("4", "4"),
                Choice("5", "5"),
                Choice("6", "6"),
                Choice("7", "7"),
                Choice("8", "8"),
                Choice("9", "9"),
                Choice("a", "a"),
                Choice("b", "b"),
                Choice("c", "c"),
                Choice("d", "d"),
                Choice("e", "e"),
                Choice("f", "f"),
            ),
            defaultValue = "0",
        ),
        Option(
            key = "ppsspp_change_mac_address11",
            label = "MAC Address Pt 11: --:--:--:--:--:x-",
            category = "network",
            choices = listOf(
                Choice("0", "0"),
                Choice("1", "1"),
                Choice("2", "2"),
                Choice("3", "3"),
                Choice("4", "4"),
                Choice("5", "5"),
                Choice("6", "6"),
                Choice("7", "7"),
                Choice("8", "8"),
                Choice("9", "9"),
                Choice("a", "a"),
                Choice("b", "b"),
                Choice("c", "c"),
                Choice("d", "d"),
                Choice("e", "e"),
                Choice("f", "f"),
            ),
            defaultValue = "0",
        ),
        Option(
            key = "ppsspp_change_mac_address12",
            label = "MAC Address Pt 12: --:--:--:--:--:-x",
            category = "network",
            choices = listOf(
                Choice("0", "0"),
                Choice("1", "1"),
                Choice("2", "2"),
                Choice("3", "3"),
                Choice("4", "4"),
                Choice("5", "5"),
                Choice("6", "6"),
                Choice("7", "7"),
                Choice("8", "8"),
                Choice("9", "9"),
                Choice("a", "a"),
                Choice("b", "b"),
                Choice("c", "c"),
                Choice("d", "d"),
                Choice("e", "e"),
                Choice("f", "f"),
            ),
            defaultValue = "0",
        ),
        Option(
            key = "ppsspp_wlan_channel",
            label = "WLAN Channel",
            category = "network",
            choices = listOf(
                Choice("Auto", "Auto"),
                Choice("1", "1"),
                Choice("6", "6"),
                Choice("11", "11"),
            ),
            defaultValue = "Auto",
        ),
        Option(
            key = "ppsspp_enable_builtin_pro_ad_hoc_server",
            label = "Enable Built-in PRO Ad Hoc Server",
            category = "network",
            choices = listOf(
                Choice("disabled", "disabled"),
                Choice("enabled", "enabled"),
            ),
            defaultValue = "disabled",
        ),
        Option(
            key = "ppsspp_change_pro_ad_hoc_server_address",
            label = "Change PRO Ad Hoc Server IP Address ('localhost' = multiple instances)",
            category = "network",
            choices = listOf(
                Choice("socom.cc", "socom.cc"),
                Choice("psp.gameplayer.club", "psp.gameplayer.club"),
                Choice("myneighborsushicat.com", "myneighborsushicat.com"),
                Choice("localhost", "localhost"),
                Choice("IP address", "IP address"),
            ),
            defaultValue = "socom.cc",
        ),
        Option(
            key = "ppsspp_pro_ad_hoc_server_address01",
            label = "PRO Ad Hoc Server IP Address Pt  1: x--.---.---.---",
            category = "network",
            choices = listOf(
                Choice("0", "0"),
                Choice("1", "1"),
                Choice("2", "2"),
                Choice("3", "3"),
                Choice("4", "4"),
                Choice("5", "5"),
                Choice("6", "6"),
                Choice("7", "7"),
                Choice("8", "8"),
                Choice("9", "9"),
            ),
            defaultValue = "0",
        ),
        Option(
            key = "ppsspp_pro_ad_hoc_server_address02",
            label = "PRO Ad Hoc Server IP Address Pt  2: -x-.---.---.---",
            category = "network",
            choices = listOf(
                Choice("0", "0"),
                Choice("1", "1"),
                Choice("2", "2"),
                Choice("3", "3"),
                Choice("4", "4"),
                Choice("5", "5"),
                Choice("6", "6"),
                Choice("7", "7"),
                Choice("8", "8"),
                Choice("9", "9"),
            ),
            defaultValue = "0",
        ),
        Option(
            key = "ppsspp_pro_ad_hoc_server_address03",
            label = "PRO Ad Hoc Server IP Address Pt  3: --x.---.---.---",
            category = "network",
            choices = listOf(
                Choice("0", "0"),
                Choice("1", "1"),
                Choice("2", "2"),
                Choice("3", "3"),
                Choice("4", "4"),
                Choice("5", "5"),
                Choice("6", "6"),
                Choice("7", "7"),
                Choice("8", "8"),
                Choice("9", "9"),
            ),
            defaultValue = "0",
        ),
        Option(
            key = "ppsspp_pro_ad_hoc_server_address04",
            label = "PRO Ad Hoc Server IP Address Pt  4: ---.x--.---.---",
            category = "network",
            choices = listOf(
                Choice("0", "0"),
                Choice("1", "1"),
                Choice("2", "2"),
                Choice("3", "3"),
                Choice("4", "4"),
                Choice("5", "5"),
                Choice("6", "6"),
                Choice("7", "7"),
                Choice("8", "8"),
                Choice("9", "9"),
            ),
            defaultValue = "0",
        ),
        Option(
            key = "ppsspp_pro_ad_hoc_server_address05",
            label = "PRO Ad Hoc Server IP Address Pt  5: ---.-x-.---.---",
            category = "network",
            choices = listOf(
                Choice("0", "0"),
                Choice("1", "1"),
                Choice("2", "2"),
                Choice("3", "3"),
                Choice("4", "4"),
                Choice("5", "5"),
                Choice("6", "6"),
                Choice("7", "7"),
                Choice("8", "8"),
                Choice("9", "9"),
            ),
            defaultValue = "0",
        ),
        Option(
            key = "ppsspp_pro_ad_hoc_server_address06",
            label = "PRO Ad Hoc Server IP Address Pt  6: ---.--x.---.---",
            category = "network",
            choices = listOf(
                Choice("0", "0"),
                Choice("1", "1"),
                Choice("2", "2"),
                Choice("3", "3"),
                Choice("4", "4"),
                Choice("5", "5"),
                Choice("6", "6"),
                Choice("7", "7"),
                Choice("8", "8"),
                Choice("9", "9"),
            ),
            defaultValue = "0",
        ),
        Option(
            key = "ppsspp_pro_ad_hoc_server_address07",
            label = "PRO Ad Hoc Server IP Address Pt  7: ---.---.x--.---",
            category = "network",
            choices = listOf(
                Choice("0", "0"),
                Choice("1", "1"),
                Choice("2", "2"),
                Choice("3", "3"),
                Choice("4", "4"),
                Choice("5", "5"),
                Choice("6", "6"),
                Choice("7", "7"),
                Choice("8", "8"),
                Choice("9", "9"),
            ),
            defaultValue = "0",
        ),
        Option(
            key = "ppsspp_pro_ad_hoc_server_address08",
            label = "PRO Ad Hoc Server IP Address Pt  8: ---.---.-x-.---",
            category = "network",
            choices = listOf(
                Choice("0", "0"),
                Choice("1", "1"),
                Choice("2", "2"),
                Choice("3", "3"),
                Choice("4", "4"),
                Choice("5", "5"),
                Choice("6", "6"),
                Choice("7", "7"),
                Choice("8", "8"),
                Choice("9", "9"),
            ),
            defaultValue = "0",
        ),
        Option(
            key = "ppsspp_pro_ad_hoc_server_address09",
            label = "PRO Ad Hoc Server IP Address Pt  9: ---.---.--x.---",
            category = "network",
            choices = listOf(
                Choice("0", "0"),
                Choice("1", "1"),
                Choice("2", "2"),
                Choice("3", "3"),
                Choice("4", "4"),
                Choice("5", "5"),
                Choice("6", "6"),
                Choice("7", "7"),
                Choice("8", "8"),
                Choice("9", "9"),
            ),
            defaultValue = "0",
        ),
        Option(
            key = "ppsspp_pro_ad_hoc_server_address10",
            label = "PRO Ad Hoc Server IP Address Pt 10: ---.---.---.x--",
            category = "network",
            choices = listOf(
                Choice("0", "0"),
                Choice("1", "1"),
                Choice("2", "2"),
                Choice("3", "3"),
                Choice("4", "4"),
                Choice("5", "5"),
                Choice("6", "6"),
                Choice("7", "7"),
                Choice("8", "8"),
                Choice("9", "9"),
            ),
            defaultValue = "0",
        ),
        Option(
            key = "ppsspp_pro_ad_hoc_server_address11",
            label = "PRO Ad Hoc Server IP Address Pt 11: ---.---.---.-x-",
            category = "network",
            choices = listOf(
                Choice("0", "0"),
                Choice("1", "1"),
                Choice("2", "2"),
                Choice("3", "3"),
                Choice("4", "4"),
                Choice("5", "5"),
                Choice("6", "6"),
                Choice("7", "7"),
                Choice("8", "8"),
                Choice("9", "9"),
            ),
            defaultValue = "0",
        ),
        Option(
            key = "ppsspp_pro_ad_hoc_server_address12",
            label = "PRO Ad Hoc Server IP Address Pt 12: ---.---.---.--x",
            category = "network",
            choices = listOf(
                Choice("0", "0"),
                Choice("1", "1"),
                Choice("2", "2"),
                Choice("3", "3"),
                Choice("4", "4"),
                Choice("5", "5"),
                Choice("6", "6"),
                Choice("7", "7"),
                Choice("8", "8"),
                Choice("9", "9"),
            ),
            defaultValue = "0",
        ),
        Option(
            key = "ppsspp_enable_upnp",
            label = "Enable UPnP (Need a few seconds to detect)",
            category = "network",
            choices = listOf(
                Choice("disabled", "disabled"),
                Choice("enabled", "enabled"),
            ),
            defaultValue = "disabled",
        ),
        Option(
            key = "ppsspp_upnp_use_original_port",
            label = "UPnP Use Original Port ('ON' = PSP compatibility)",
            category = "network",
            choices = listOf(
                Choice("disabled", "disabled"),
                Choice("enabled", "enabled"),
            ),
            defaultValue = "enabled",
        ),
        Option(
            key = "ppsspp_port_offset",
            label = "Port Offset ('0' = PSP compatibility)",
            category = "network",
            choices = listOf(
                Choice("0", "0"),
                Choice("1000", "1000"),
                Choice("2000", "2000"),
                Choice("3000", "3000"),
                Choice("4000", "4000"),
                Choice("5000", "5000"),
                Choice("6000", "6000"),
                Choice("7000", "7000"),
                Choice("8000", "8000"),
                Choice("9000", "9000"),
                Choice("10000", "10000"),
                Choice("11000", "11000"),
                Choice("12000", "12000"),
                Choice("13000", "13000"),
                Choice("14000", "14000"),
                Choice("15000", "15000"),
                Choice("16000", "16000"),
                Choice("17000", "17000"),
                Choice("18000", "18000"),
                Choice("19000", "19000"),
                Choice("20000", "20000"),
                Choice("31000", "31000"),
                Choice("32000", "32000"),
                Choice("33000", "33000"),
                Choice("34000", "34000"),
                Choice("35000", "35000"),
                Choice("36000", "36000"),
                Choice("37000", "37000"),
                Choice("38000", "38000"),
                Choice("39000", "39000"),
                Choice("40000", "40000"),
                Choice("41000", "41000"),
                Choice("42000", "42000"),
                Choice("43000", "43000"),
                Choice("44000", "44000"),
                Choice("45000", "45000"),
                Choice("46000", "46000"),
                Choice("47000", "47000"),
                Choice("48000", "48000"),
                Choice("49000", "49000"),
                Choice("50000", "50000"),
                Choice("51000", "51000"),
                Choice("52000", "52000"),
                Choice("53000", "53000"),
                Choice("54000", "54000"),
                Choice("55000", "55000"),
                Choice("56000", "56000"),
                Choice("57000", "57000"),
                Choice("58000", "58000"),
                Choice("59000", "59000"),
                Choice("60000", "60000"),
                Choice("61000", "61000"),
                Choice("62000", "62000"),
                Choice("63000", "63000"),
                Choice("64000", "64000"),
                Choice("65000", "65000"),
            ),
            defaultValue = "0",
        ),
        Option(
            key = "ppsspp_minimum_timeout",
            label = "Minimum Timeout (Override in ms, '0' = default)",
            category = "network",
            choices = listOf(
                Choice("0", "0"),
                Choice("100", "100"),
                Choice("200", "200"),
                Choice("300", "300"),
                Choice("400", "400"),
                Choice("500", "500"),
                Choice("600", "600"),
                Choice("700", "700"),
                Choice("800", "800"),
                Choice("900", "900"),
                Choice("1000", "1000"),
                Choice("1100", "1100"),
                Choice("1200", "1200"),
                Choice("1300", "1300"),
                Choice("1400", "1400"),
                Choice("1500", "1500"),
                Choice("1600", "1600"),
                Choice("1700", "1700"),
                Choice("1800", "1800"),
                Choice("1900", "1900"),
                Choice("2000", "2000"),
                Choice("3100", "3100"),
                Choice("3200", "3200"),
                Choice("3300", "3300"),
                Choice("3400", "3400"),
                Choice("3500", "3500"),
                Choice("3600", "3600"),
                Choice("3700", "3700"),
                Choice("3800", "3800"),
                Choice("3900", "3900"),
                Choice("4000", "4000"),
                Choice("4100", "4100"),
                Choice("4200", "4200"),
                Choice("4300", "4300"),
                Choice("4400", "4400"),
                Choice("4500", "4500"),
                Choice("4600", "4600"),
                Choice("4700", "4700"),
                Choice("4800", "4800"),
                Choice("4900", "4900"),
                Choice("5000", "5000"),
            ),
            defaultValue = "0",
        ),
        Option(
            key = "ppsspp_forced_first_connect",
            label = "Forced First Connect (Faster connect)",
            category = "network",
            choices = listOf(
                Choice("disabled", "disabled"),
                Choice("enabled", "enabled"),
            ),
            defaultValue = "disabled",
        ),
    )

    private val optionsByKey: Map<String, Option> by lazy { optionList.associateBy { it.key } }

    private val audioKeys: Set<String> =
        optionList.map { it.key }.filter { it.contains("audio") }.toSet()

    /** Keys driven by dedicated app-level controls (renderer and upscale). */
    private val managedKeys = setOf(
        "ppsspp_backend",
        "ppsspp_software_rendering",
        "ppsspp_internal_resolution",
    )
    private val unavailableRendererKeys = setOf(
        "ppsspp_mulitsample_level",
        "ppsspp_texture_shader",
    )

    fun all(): List<Option> = optionList

    fun categories(): List<Category> = categoryList

    fun forCategory(categoryKey: String): List<Option> = optionList.filter { it.category == categoryKey }

    fun option(key: String): Option? = optionsByKey[key]

    fun isManagedKey(key: String): Boolean = key in managedKeys

    fun categoryLabel(categoryKey: String): String =
        categoryList.firstOrNull { it.key == categoryKey }?.label ?: categoryKey

    fun categoryDescription(categoryKey: String): String =
        categoryList.firstOrNull { it.key == categoryKey }?.description.orEmpty()

    /** Video tab: rendering and display options. */
    fun graphicsOptions(): List<Option> =
        forCategory("video").filterNot {
            it.key in audioKeys || isManagedKey(it.key) || it.key in unavailableRendererKeys
        }

    /** System & performance tab: system and emulation hacks. */
    fun emulationOptions(): List<Option> =
        (forCategory("system") + forCategory("hacks"))
            .filterNot { it.key in audioKeys || isManagedKey(it.key) }

    /** Small set of system switches useful during play; detailed tuning stays in settings. */
    fun gameMenuEmulationOptions(): List<Option> = listOfNotNull(
        option("ppsspp_memstick_inserted"),
        option("ppsspp_language"),
    )

    /** PSP ad hoc, WLAN, and port configuration. */
    fun networkOptions(): List<Option> =
        forCategory("network").filterNot { isManagedKey(it.key) }

    /** Controls tab: input options. */
    fun controlsOptions(): List<Option> =
        forCategory("input").filterNot { isManagedKey(it.key) }

    /** Audio tab: every option that targets audio output. */
    fun audioOptions(): List<Option> =
        optionList.filter { it.key in audioKeys }.filterNot { isManagedKey(it.key) }

    /** Graphics section of the in-game menu. */
    fun gameMenuGraphicsOptions(): List<Option> = listOfNotNull(
        option("ppsspp_frameskip"),
        option("ppsspp_auto_frameskip"),
        option("ppsspp_texture_scaling_type"),
        option("ppsspp_texture_scaling_level"),
        option("ppsspp_texture_deposterize"),
        option("ppsspp_texture_anisotropic_filtering"),
        option("ppsspp_texture_filtering"),
        option("ppsspp_smart_2d_texture_filtering"),
        option("ppsspp_texture_replacement"),
        option("ppsspp_gpu_hardware_transform"),
        option("ppsspp_skip_buffer_effects"),
        option("ppsspp_skip_gpu_readbacks"),
        option("ppsspp_spline_quality"),
        option("ppsspp_lower_resolution_for_effects"),
        option("ppsspp_frame_duplication"),
        option("ppsspp_inflight_frames"),
        option("ppsspp_detect_vsync_swap_interval"),
    )

    /** Controls section of the in-game menu. */
    fun gameMenuControlsOptions(): List<Option> = listOfNotNull(
        option("ppsspp_button_preference"),
        option("ppsspp_analog_is_circular"),
        option("ppsspp_analog_deadzone"),
        option("ppsspp_analog_sensitivity"),
    )
}
